n = str(input('Digite algo:'))
print(type(n))
print('{} é alfabético ? {}.'.format(n, n.isalpha()))
print('{} é numérico? {}.'.format(n, n.isnumeric()))
print('{} é maiúsculo? {}.'.format(n, n.isupper()))
print('{} é minúsculo? {}.'.format(n, n.islower()))
print('{} é apenas espaço? {}.'.format(n, n.isspace()))
print('{} é alfanumérico? {}.'.format(n, n.isalnum()))
print('{} é decimal? {}.'.format(n, n.isdecimal()))
print('{} é capitalizada? {}.'.format(n, n.istitle()))
